FROM ubuntu
MAINTAINER SamFrier

RUN apt-get update
RUN apt-get install -y wget

# Get install files
RUN wget http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+xenial_all.deb
RUN dpkg -i zabbix-release_3.0-1+xenial_all.deb
RUN apt-get update

# Install Zabbix agent
RUN apt-get install -y zabbix-agent

# Configure agent
RUN sed -i '95s/.*/Server=zabbix-server/' /etc/zabbix/zabbix_agentd.conf
RUN sed -i '136s/.*/ServerActive=zabbix-server/' /etc/zabbix/zabbix_agentd.conf
RUN /etc/init.d/zabbix-agent restart

# Run agent
EXPOSE 10050
ENTRYPOINT /etc/init.d/zabbix-agent start && bash
